### ISSUE TITLE
Port for Firefox Quantum

### ISSUE THREAD

**Issue by techexo** [Devenet/SimpleShare#3]
Hello everyone,

I was wondering if the developers would consider porting this extension on Firefox Quantum, now that is is compatible with WebExtensions. Indeed, all the previous add-ons for sharing on Shaarli with Firefox are now deprecated; and it is probably easier to port from Chrome to Firefox Quantum than to rewrite something from scratch.

Thanks a lot in advance, do not hesitate to ask for more information if needed.

Best regards

**Comment by Devenet** [comment]
Hi techexo

It is not planned to port this Chrome extension on Firefox WebExtension.

Like you, I have the same problem with Firefox Quantum, I'm unable to easily share an URL on my Shaarli instance. If there is no extension soon available, I may try to port this extension on Firefox sooner.

Regards

**Comment by techexo** [comment]
@Devenet A user on Shaarli's github proposed an add-on that he's developed quickly: https://github.com/ikipatang/shaarli-web-extension

It seems to have some encoding issues on Linux, but it works on Windows.

This discussion could also be of interest for you: https://github.com/shaarli/Shaarli/issues/1023

Cheers

**Comment by techexo** [comment]
Hi,
As alternatives are being developed, I close this issue :)

Cheers
